font_family JetBrainsMono Nerd Font
font_size 11.0

background #09152F
foreground #D9CFE0
background_opacity 0.94

selection_background #2C1F4E
selection_foreground #EF6261

# Cursor
cursor #EF6261
cursor_text_color #09152F
cursor_trail 1
cursor_trail_decay 0.05 0.25
cursor_trail_start_threshold 1
cursor_trail_color #EF6261

active_border_color #EF6261
inactive_border_color #2C1F4E
bell_border_color #B63A6C

active_tab_foreground #EF6261
active_tab_background #0A152E
inactive_tab_foreground #9B346B
inactive_tab_background #09152F
tab_bar_background #09152F

# Normal ANSI colors
# All text colors are kept distinct enough from the navy background.
color0  #3A2850
color1  #B63A6C
color2  #7A3A70
color3  #EF6261
color4  #33468A
color5  #9B346B
color6  #79416F
color7  #D9CFE0

# Bright ANSI colors
color8  #523B69
color9  #FF6470
color10 #D24B78
color11 #FF746F
color12 #5268A8
color13 #B95C98
color14 #986090
color15 #F3EAF2

window_padding_width 10
placement_strategy center

enable_audio_bell no
visual_bell_duration 0
confirm_os_window_close 0
