font_family JetBrainsMono Nerd Font
font_size 11.0

background #09152F
foreground #D9CFE0
background_opacity 0.94

selection_background #2C1F4E
selection_foreground #EF6261

# Cursor
cursor #EF6261
cursor_text_color #09152F
cursor_trail 1
cursor_trail_decay 0.05 0.25
cursor_trail_start_threshold 1
cursor_trail_color #EF6261

active_border_color #EF6261
inactive_border_color #2C1F4E
bell_border_color #B63A6C

active_tab_foreground #EF6261
active_tab_background #0A152E
inactive_tab_foreground #9B346B
inactive_tab_background #09152F
tab_bar_background #09152F

color0 #09152F
color1 #B63A6C
color2 #5F295D
color3 #EF6261
color4 #0F183D
color5 #9B346B
color6 #67315F
color7 #D9CFE0

color8 #2C1F4E
color9 #EF6261
color10 #B63A6C
color11 #EF6261
color12 #0F183D
color13 #9B346B
color14 #67315F
color15 #F3EAF2

window_padding_width 10
placement_strategy center

enable_audio_bell no
visual_bell_duration 0
confirm_os_window_close 0
