[Appearance]
style=Fusion
custom_palette=true
color_scheme_path=/home/alice/.config/qt6ct/colors/AliceNight.conf

[Interface]
activate_item_on_single_click=1
dialog_buttons_have_icons=true
menus_have_icons=true
show_shortcuts_in_context_menus=true
toolbutton_style=4

[Fonts]
general=JetBrainsMono Nerd Font,11
fixed=JetBrainsMono Nerd Font,11
